### ISSUE TITLE
Docker Compose 2.1 doesn't work when Creating a Stack in Portainer

### ISSUE THREAD

**Issue by geoffrothman** [doshyt/pandora-docker-compose#1]
It only accepts v 2.0 so i just took out the healthcheck and changed the syntax of depends_on . to get past the syntax checker. here it is:

version: '2'

services:
  pandora-mysql:
    image: pandorafms/pandorafms-mysql:6
    volumes:
      - "./db:/var/lib/mysql:rw"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      MYSQL_ROOT_PASSWORD: "ENTERYOURPASSWD"
      MYSQL_DATABASE: "pandora"
      MYSQL_USER: "pandora"
      MYSQL_PASSWORD: "ENTERYOURPASSWD"
    networks:
      pandora:
        ipv4_address: 172.35.0.2

  pandora-server:
    image: pandorafms/pandorafms-server:6
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./server-config/postfix/main.cf:/etc/postfix/main.cf"
    ports:
      - "41121:41121"
    links:
    - "pandora-mysql:mysql"
    networks:
      pandora:
        ipv4_address: 172.35.0.4
    depends_on:
    - pandora-mysql
    environment:
      PANDORA_DB_HOST: "172.35.0.2:3306"
      PANDORA_DB_USER: "pandora"
      PANDORA_DB_PASSWORD: "ENTERYOURPASSWD"

  pandora-console:
    image: pandorafms/pandorafms-console:6
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "8080:80"
      - "8022:8022"
      - "8023:8023"
    networks:
      pandora:
        ipv4_address: 172.35.0.3
    depends_on:
    - pandora-mysql
    links:
    - "pandora-mysql:mysql"
    environment:
      PANDORA_DB_HOST: "172.35.0.2:3306"
      PANDORA_DB_USER: "pandora"
      PANDORA_DB_PASSWORD: "ENTERYOURPASSWD"

networks:
  pandora:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: "172.35.0.0/24"
        gateway: "172.35.0.1"

**Comment by doshyt** [comment]
Hi, appreciate your help!

I formatted and uploaded the version for 2.1 as `docker-compose-21.yml` : https://github.com/doshyt/pandora-docker-compose/commit/adb91a2117cc52fb0f9047d81c69d558fbd23167

Thanks for contributing!
